<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.Azure" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceDefaults\ServiceDefaults.csproj" />
    <ProjectReference Include="..\ProcessingService.Infrastructure\ProcessingService.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared.ObjectStorage.Infrastructure\Shared.ObjectStorage.Infrastructure.csproj" />
  </ItemGroup>
</Project>
