<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProcessingService.Application\ProcessingService.Application.csproj" />
    <ProjectReference Include="..\Shared.ObjectStorage.Infrastructure\Shared.ObjectStorage.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared.Repository.Infrastructure\Shared.Repository.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" />
    <PackageReference Include="Azure.Storage.Blobs" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="MetadataExtractor" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="MongoDB.Driver" />
  </ItemGroup>
</Project>
